services:
  api_lab02:
    container_name: api_lab02
    build: application/
    environment:
      - DB_HOST=postgres_lab02
      - DB_PORT=5432
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    ports:
      - 8000:8000
    networks:
      - arch-network_lab02
    depends_on:
      - db_lab02
      
  db_lab02:
    container_name: postgres_lab02
    image: postgres:15
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=stud
      - POSTGRES_PASSWORD=stud
      - PGDATA=/data/postgres
      - POSTGRES_DB=archdb
    volumes:
      - db_lab02:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - arch-network_lab02

  pgadmin_lab02:
    container_name: pgadmin4_lab02
    image: dpage/pgadmin4
    restart: always
    user: '$UID:$GID'
    ports:
      - "5050:80"
    volumes:
     - ./docker_pg_data/pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - db_lab02
    networks:
      arch-network_lab02:

volumes:
  db_lab02:
  pgadmin-data_lab02:

networks:
  arch-network_lab02:
    driver: "bridge"
    external: false
